### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by ghost** [MoritzGoeckel/Skribbl.io-Bot#1]
How can I use this script?

**Comment by MoritzGoeckel** [comment]
Hi,

there are many plugins for the various browsers that enable you to load java script files.
Chrome has one called "User JavaScript and CSS" for example.

When loaded, the script does its thing. You dont need to call any function. Just go to scribbl.io, start a game and load the script.

Hope that helps :)

Best regards
Moritz
